[package]
authors = ["Wonderland"]
name = "youdusa-rs"
description = "Take a Medusa trace as input, parse it and create Foundry reproducer function for every failing properties"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/defi-wonderland/youdusa-rs"

[lib]
name = "youdusa"
path = "src/lib.rs"

[[bin]]
name = "youdusa"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
env_logger = "0.10"
