[package]
authors = ["Wonderland"]
name = "youdusa-rs"
description = "Handle Medusa fuzzing and generate forge tests for failed properties"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/defi-wonderland/youdusa-rs"

[[bin]]
name = "youdusa"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.92"
clap = "4.5.21"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
env_logger = "0.10"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
